development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("SCALINGO_REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: wagons_cup_production
